name: Build and Server Update
on:
  workflow_dispatch:
    inputs:
      profile:
        type: choice
        description: Build profile to use
        options:
          - development
          - preview
          - production

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm --prefix server install

      - name: Load the Environment Variables
        run: |
          echo "PORT=5000" >> server/.env
          echo "CONNECTION_STRING=${{ secrets.CONNECTION_STRING }}" >> server/.env

      - name: Test
        run: npm --prefix server run test

      - name: Build
        run: |
          cd server
          npm run build

      - name: Netlify Deployment
        uses: netlify/actions/cli@master
        with:
          args: deploy --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
