name: "J1 Frontend"

on:
  push:
    branches:
      - main

  workflow_dispatch:
    branches:
      - dev
    # Can add push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.0

      - name: Install dependencies
        run: |
          cd client
          npm install
          cd ../server
          npm install

      - name: Build and Test React Native
        run: |
          cd client
          npm run build
          npm test

      - name: Build and Test Node Server
        run: |
          cd server
          npm run build
          npm test
